go-service:
  replicaCount: 10

  image:
    repository: techacademyti/go-service-reviews
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  fullnameOverride: "go-service-reviews-2"

  podAnnotations: {
        "dapr.io/enabled": "true",
        "dapr.io/app-id": "reviews"
        }