go-service:
  replicaCount: 1

  image:
    repository: techacademyti/go-service-reviews
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  fullnameOverride: "go-service-reviews-2"

  podAnnotations: {
        "dapr.io/enabled": "true",
        "dapr.io/app-id": "reviews"
        }
  ingress:
    enabled: true
    host: reviews.143-244-213-51.nip.io
    path: /
